/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'restaurantName' : IDL.Text,
});
export const MenuPhoto = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addMenuPhotoEN' : IDL.Func([IDL.Text, ExternalBlob, IDL.Text], [], []),
  'addMenuPhotoES' : IDL.Func([IDL.Text, ExternalBlob, IDL.Text], [], []),
  'addMenuPhotosEN' : IDL.Func(
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Text,
            'blob' : ExternalBlob,
            'name' : IDL.Text,
          })
        ),
      ],
      [],
      [],
    ),
  'addMenuPhotosES' : IDL.Func(
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Text,
            'blob' : ExternalBlob,
            'name' : IDL.Text,
          })
        ),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMenuPhotoEN' : IDL.Func([IDL.Text], [], []),
  'deleteMenuPhotoES' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
  'getMenuPhotosEN' : IDL.Func([], [IDL.Vec(MenuPhoto)], ['query']),
  'getMenuPhotosES' : IDL.Func([], [IDL.Vec(MenuPhoto)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderMenuPhotosEN' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'reorderMenuPhotosES' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateContactInfo' : IDL.Func([ContactInfo], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactInfo = IDL.Record({
    'email' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'restaurantName' : IDL.Text,
  });
  const MenuPhoto = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addMenuPhotoEN' : IDL.Func([IDL.Text, ExternalBlob, IDL.Text], [], []),
    'addMenuPhotoES' : IDL.Func([IDL.Text, ExternalBlob, IDL.Text], [], []),
    'addMenuPhotosEN' : IDL.Func(
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Text,
              'blob' : ExternalBlob,
              'name' : IDL.Text,
            })
          ),
        ],
        [],
        [],
      ),
    'addMenuPhotosES' : IDL.Func(
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Text,
              'blob' : ExternalBlob,
              'name' : IDL.Text,
            })
          ),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMenuPhotoEN' : IDL.Func([IDL.Text], [], []),
    'deleteMenuPhotoES' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
    'getMenuPhotosEN' : IDL.Func([], [IDL.Vec(MenuPhoto)], ['query']),
    'getMenuPhotosES' : IDL.Func([], [IDL.Vec(MenuPhoto)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderMenuPhotosEN' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'reorderMenuPhotosES' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateContactInfo' : IDL.Func([ContactInfo], [], []),
  });
};

export const init = ({ IDL }) => { return []; };